import Head from 'next/head'

export default function AboutMe() {
  return (
    <>
      <Head>
        <title>About | MR</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main>
        <div className="container-flex-full">
          <div className={`copy-max-width`}>
            <h1 className={"blue-pink"}>About Me</h1>
            <p>
              I started my web development journey back in 2013 when I made my first Wordpress site.
              The idea was to build a website to sell products online and become a millionaire. As I was making this
              happen I realized I needed to know a bit more about the coding side of things in order to make the
              site work how I wanted it to. That's when I decided I get some schooling in the subject and signed up
              for the fast track program at SAIT (Southern Alberta Institute of Technology). My practicum for the
              program led me to my first junior role as a dev and it was there that I fell in love with coding. I've
              been working on websites ever since.
            </p>
            <p className={"text-center"}>{`</>`}</p>
          </div>
        </div>
      </main>
    </>
  )
}
