import Head from 'next/head'
import Form from "@/components/form/contact-form";

const contactMethods = [
  {name: 'Phone', value: 'Email me for my number please.'},
  {name: 'Email', value: 'mrobinson537@live.ca'},
  {name: 'LinkedIn', value: 'https://www.linkedin.com/in/mattrobinson537/'}
]

export default function Contact() {
  return (
    <>
      <Head>
        <title>Contact | MR</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main>
        <div className="container-flex-full">
          <div className={`copy-max-width`}>
            <h1 className={"blue-pink"}>Contact</h1>
            <p className={"text-center"}>You can find me on <a href={"https://www.linkedin.com/in/mattrobinson537/"}>LinkedIn</a>.</p>
            <p className={"text-center"}>Cheers!</p>
            {/*<Form />*/}
          </div>
        </div>
      </main>
    </>
  )
}
