import Head from 'next/head'
import Link from 'next/link';

const myExperience = [
  {
    company: 'Logitech',
    position: 'Frontend Developer',
    timeframe: 'Jan 2021 - Mar 2023',
    url: '//www.logitech.com',
    description: 'Deliver high quality production code for the suite of Logitech ecommerce websites. Improved performance, SEO, and ADA compliance. Led the frontend maintenance of the Logitech G site.',
    urls: [
      {label: 'Logitech', url: '//www.logitech.com'},
      {label: 'Logitech Gaming', url: '//www.logitechg.com'},
      {label: 'Astro', url: '//www.astrogaming.com'},
      {label: 'Ultimate Ears', url: '//www.ultimateears.com'},
      {label: 'Jaybird', url: '//www.jaybirdsport.com'},
    ],
    tech: ['Javascript','ES5/6', 'Typescript', 'SCSS', 'AEM']
  },
  {
    company: 'Evans Hunt',
    position: 'Web Developer',
    timeframe: 'Sept 2017 - Dec 2020',
    url: '//www.evanshunt.com',
    description: 'Developed, maintained, and shipped production code for a variety of client websites. Clients included Ikon Pass, Alterra, Nutrien, Benevity, and many more.',
    urls: [
      {label: 'Ikon Pass', url: '//www.ikonpass.com'},
      {label: 'Alterra', url: '//www.alterramtn.co/'},
      {label: 'Benevity', url: '//benevity.com/'}
    ],
    tech: ['React', 'Next.js', 'Javascript', 'SCSS', 'Contentful', 'PHP', 'Silverstripe']
  },
  {
    company: 'Live Out There Inc.',
    position: 'Web Developer',
    timeframe: 'Jan 2014 - Sept 2017',
    url: '//www.liveoutthere.com',
    description: 'Built, maintained, and improved upon the ecommerce website as required. Collaborated with designers to build a beautiful shopping experience. Worked alongside the marketing team to enable analytics, A/B testing, merchandising, and email campaigns.',
    urls: [
      {label: 'Live Out There', url: '//www.liveoutthere.com', live: false},
    ],
    tech: ['Javascript', 'Angular', 'React', 'SCSS', 'Magento', 'PHP']
  }
]

export default function Experience() {
  return (
    <>
      <Head>
        <title>Experience | MR</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main>
        <div className="container-flex-full">
          <div className={`container`}>
            <h1 className={"blue-pink"}>Experience</h1>

            <div className={"timeline"}>

              {myExperience.map((item, i) => {
                return (
                  <div className="timeline-item" key={i}>

                    <div className="timeline-item-timeframe">
                      {item.timeframe}
                    </div>

                    <div className="timeline-item-content">
                      <h3 className="timeline-item-title">{item.position} · <Link href={item.url}>{item.company}</Link></h3>
                      <div className="timeline-item-description">
                        {item.description}
                      </div>
                      <div className="timeline-item-links">
                        {item.urls.map((url, i) => {
                          return (
                            <div className="timeline-item-link" key={i}><Link href={url.url}>{url.label}</Link></div>
                          )
                        })}
                      </div>
                      <div className="timeline-item-techs">
                        {item.tech.map((techname, i) => {
                          return (
                            <div className="timeline-item-tech" key={i}>{techname}</div>
                          )
                        })}
                      </div>
                    </div>
                  </div>
                )
              })}
            </div>

          </div>
        </div>
      </main>
    </>
  )
}
