import Head from 'next/head'
import FlexCards from '@/components/flex-cards'

const myHobbies = [
  {name: 'Rock climbing', imgPath: '/img/rock-climbing.jpeg'},
  {name: 'Ice climbing', imgPath: '/img/ice-climbing.jpeg'},
  {name: 'Mountaineering', imgPath: '/img/mountaineering.jpeg'},
  {name: 'Snowboarding', imgPath: '/img/snowboarding.jpeg'},
  {name: 'Backcountry Skiing', imgPath: '/img/bc-skiing.jpeg'}
]

export default function Hobbies() {
  return (
    <>
      <Head>
        <title>Hobbies | MR</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main>
        <div className="container-flex-full">
          <div className="container">
            <div>
              <h1 className={"text-center main-title blue-pink"}>Hobbies</h1>
            </div>
            <FlexCards myHobbies={myHobbies} bordered={false} />
          </div>
        </div>
      </main>
    </>
  )
}
