import Head from 'next/head'

const myTech = [
  {
    category: 'Frontend',
    tech: [
      {name: 'HTML & HTML5'},
      {name: 'CSS, SCSS, LESS'},
      {name: 'Vanilla Javascript'},
      {name: 'React'},
      {name: 'NextJS'},
      {name: 'Angular'},
      {name: 'jQuery'},
      {name: 'NodeJS'},
      {name: 'Typescript'},
      {name: 'Google App Script'}
    ]
  },
  {
    category: 'Backend',
    tech: [
      {name: 'PHP'},
      {name: 'SQL'},
      {name: 'Google BigQuery'},
      {name: 'Elasticsearch'}
    ]
  },
  {
    category: 'Dev Tools',
    tech: [
      {name: 'Git'},
      {name: 'npm/node'},
      {name: 'Webpack'},
      {name: 'Gulp'},
      {name: 'Grunt'},
      {name: 'Parcel'},
    ]
  },
  {
    category: 'CMS',
    tech: [
      {name: 'Contentful'},
      {name: 'Silverstripe'},
      {name: 'Magento'},
      {name: 'Drupal'},
      {name: 'Wordpress'},
      {name: 'Squarespace'},
      {name: 'Shopify'},
      {name: 'AEM'},
    ]
  },
  {
    category: 'Web Services',
    tech: [
      {name: 'AWS'},
      {name: 'Netlify'},
      {name: 'Jenkins'},
      {name: 'Heroku'},
      {name: 'Beanstalk'}
    ]
  },
  {
    category: 'Design Programs',
    tech: [
      {name: 'Photoshop'},
      {name: 'Sketch'},
      {name: 'Abstract'},
      {name: 'Figma'}
    ]
  }
]

export default function Technologies() {
  return (
    <>
      <Head>
        <title>Tech | MR</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main>
        <div className="">
          <div className={`container-flex-full`}>
            <div className="named-list-wrap">
              <h1 className={"main-title blue-pink"}>Tech</h1>
              <p className={"main-subtitle text-center"}>Some of the web technologies that I have worked with over the years.</p>

              {myTech.map((item, key) => {
                return (
                  <div key={key} className="named-list">
                    <h3 className="named-list-title">{item.category}</h3>
                    <ul>
                      {item.tech.map((tech, key2) => {
                        return (
                          <li key={key2}>{tech.name}</li>
                        )
                      })}
                    </ul>
                  </div>
                )
              })}
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
