import Head from 'next/head'
import Link from 'next/link'

const myWork = [
  {label: 'Logitech', url: 'www.logitech.com', description: 'Several e-commerce websites focused on selling consumer electronics.', urls: [
    {url: 'www.logitech.com'},
    {url: 'www.logitechg.com'},
    {url: 'www.astrogaming.com'},
    {url: 'www.ultimateears.com'},
    {url: 'www.jaybirdsport.com'},
  ]},
  {label: 'Ikon Pass', url: 'www.ikonpass.com', description: 'A marketing website built to sell ski passes to the masses. Built with React and Contentful.'},
  {label: 'CMH Heli Skiing', url: 'www.cmhheli.com/', description: 'A marketing website built to sell and book helicopter driven adventures. Built with React and Contentful.'},
  {label: 'EvansHunt', url: 'www.evanshunt.com', description: 'A marketing website built to showcase a digital agencies services. Built with React (NextJS) and Contentful.'},
  {label: 'Live Out There', url: 'www.liveoutthere.com', description: 'An E-Commerce website focused on selling outdoor apparel and gear. Built with Magento, and utilized some Angular.'}
]

export default function Work() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main>
        <div className="container-flex-full">
          <div className={`copy-max-width`}>
            <h1>Work</h1>
            {myWork.map((item, i) => {
              return (
                <div key={i}>
                  <h2>{item.label}</h2>
                  <p>{item.description}</p>
                  {item.urls && item.urls.map((url, k) => {
                    return (
                      <div key={k}>
                        <Link href={url.url}>{url.label}</Link>
                      </div>
                    )
                  })}
                </div>
              )
            })}
          </div>
        </div>
      </main>
    </>
  )
}
